name: ci

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1 # v6.0.1

      - name: Set up Go
        uses: actions/setup-go@v6.2.0 # v6.2.0
        with:
          go-version: "1.26.0"
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v9.1.0 # v9.1.0
        with:
          version: v2.9

      - name: Lint GitHub Actions
        uses: raven-actions/actionlint@v2.1.1 # v2.1.1
        with:
          fail-on-error: true
          pyflakes: false

      - name: Install Task
        uses: go-task/setup-task@v1.0.0 # v1.0.0
        with:
          version: 3.x

      - name: Create bin directory
        run: mkdir -p "$HOME/go/bin"

      - name: Build
        run: task build

      - name: Save binary
        run: cp ./bin/docker-agent "$RUNNER_TEMP/docker-agent-${{ github.run_id }}"

      # - name: Run tests
      #   run: |
      #     task test
      #     task test-binary

  release:
    needs: [build-and-test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1 # v6.0.1

      - name: Restore binary
        run: mkdir -p ./bin && cp "$RUNNER_TEMP/docker-agent-${{ github.run_id }}" ./bin/docker-agent

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.2 # v2.2.2
        with:
          files: ./bin/docker-agent
          generate_release_notes: true
